[profiles.mizu_demo]
mode = "strict"
runtime = "sip"

[profiles.mizu_demo.account]
aor = "sip:1111@demo.mizu-voip.com:37075"
registrar = "sip:demo.mizu-voip.com:37075"
username = "1111"
password = "1111xxx"
remote_host = "demo.mizu-voip.com"
remote_port = 37075

[profiles.mizu_demo.media]
codecs = ["PCMU", "PCMA"]
