[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sipx"
version = "0.0.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=14.1.0",
    "typer>=0.17.4",
    "textual>=6.1.0",
]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.3.0",
    "ruff>=0.12.12",
    "taskipy>=1.14.1",
    "ty>=0.0.1a20",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["sipx*"]
exclude = ["docker*", "docs*", "examples*", "tests*"]

[tool.setuptools.package-data]
sipx = ["py.typed"]
