[project]
name = "sipx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.1.0",
    "textual>=6.1.0",
    "textual-dev>=1.8.0",
    "typer>=0.17.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.3.0",
    "ruff>=0.12.12",
    "taskipy>=1.14.1",
    "ty>=0.0.1a20",
]
