version: "3.8"

services:
    asterisk:
        build: .
        container_name: sipx-asterisk
        hostname: asterisk
        restart: unless-stopped

        volumes:
            - ./config:/etc/asterisk:ro
            - asterisk-data:/var/lib/asterisk
            - asterisk-spool:/var/spool/asterisk
            - asterisk-log:/var/log/asterisk

        environment:
            - TZ=America/Sao_Paulo

        ports:
            - "5060:5060/udp"
            - "5060:5060/tcp"
            - "10000-10099:10000-10099/udp"
            - "5038:5038/tcp"

        networks:
            - sipx-network

networks:
    sipx-network:
        driver: bridge

volumes:
    asterisk-data:
    asterisk-spool:
    asterisk-log:
