[global]
type = global
endpoint_identifier_order = username,ip,anonymous

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[anonymous]
type = endpoint
context = sipx-lab
disallow = all
allow = ulaw,alaw
direct_media = no

[1000]
type = endpoint
context = sipx-lab
disallow = all
allow = ulaw,alaw
aors = 1000-aor
direct_media = no

[1000-aor]
type = aor
max_contacts = 5

[alice]
type = endpoint
context = sipx-lab
disallow = all
allow = ulaw,alaw
aors = alice-aor
auth = alice-auth
direct_media = no

[alice-aor]
type = aor
max_contacts = 5

[alice-auth]
type = auth
auth_type = userpass
username = alice
password = alice
